[package]
name = "desk_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
desk_core.workspace = true
desk_markdown = { path = "../markdown" }
desk_motion = { workspace = true }
desk_tiling.workspace = true
flume = { version = "0.11.1", default-features = false, features = ["async"] }
gpui.workspace = true
serde_json = "1.0.144"

[lints]
workspace = true
