package report

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	DataFile   = "reports.json"
	ViewerFile = "index.html"
)

type Data struct {
	Answers           Answers       `json:"answers"`
	Wiring            []Wiring      `json:"what_decides_what"`
	MethodTable       string        `json:"what_decides_what_read_from"`
	Judgments         []JudgmentRow `json:"judgments"`
	Reports           []Report      `json:"reports"`
	NoReport          []Package     `json:"benches_with_no_dated_report"`
	Counts            Counts        `json:"counts"`
	WithdrawalsLiveIn string        `json:"withdrawals_declared_from_outside_live_in"`
	GeneratedBy       string        `json:"generated_by"`
}

func (d Data) ComparedDecisions() int {
	compared := 0
	for _, row := range d.Judgments {
		if row.Compared() {
			compared++
		}
	}
	return compared
}

func (d Data) PointsOn() Figure {
	on := 0
	for _, row := range d.Wiring {
		if row.On {
			on++
		}
	}
	return countFigure(on, fmt.Sprintf("of %d decision points", len(d.Wiring)))
}

func (d Data) outOfDecisions(count int) Figure {
	return countFigure(count, fmt.Sprintf("of %d decisions", len(d.Judgments)))
}

func (d Data) JSON() ([]byte, error) {
	body, err := json.MarshalIndent(d, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(body, '\n'), nil
}

func (d Data) Markdown() string {
	doc := &strings.Builder{}
	doc.WriteString("# What bench has measured\n\n")
	fmt.Fprintf(doc, "%s compared against a cheaper method, %d not compared.",
		d.outOfDecisions(d.ComparedDecisions()), len(d.Judgments)-d.ComparedDecisions())
	for _, stat := range d.Answers.JevCosts {
		fmt.Fprintf(doc, " %s: %s, %s.", stat.Label, stat.Figure, stat.Note)
	}
	fmt.Fprintf(doc, "\n\nGenerated by `%s`. `bench/report/%s` is the same data with a viewer over it and fetches nothing. `%s` carries the line of the report every figure below was read from.\n\n",
		d.GeneratedBy, ViewerFile, AnswersPath)

	writeRefused(doc, d.Answers.Arms)
	writeRefused(doc, d.Answers.Versions)
	writeWiring(doc, d)
	writeJudgments(doc, d.Judgments)
	writeReports(doc, d)
	return doc.String()
}

func writeRefused(doc *strings.Builder, section Refused) {
	fmt.Fprintf(doc, "## %s\n\nNo answer today. %s\n", section.Question, section.Because)
	for _, group := range []struct {
		heading string
		claims  []Claim
	}{{"What exists", section.WhatExists}, {"What it would take", section.WhatItWouldTake}} {
		fmt.Fprintf(doc, "\n%s:\n\n", group.heading)
		for _, claim := range group.claims {
			fmt.Fprintf(doc, "- %s\n", claim.Text)
		}
	}
	fmt.Fprintf(doc, "\nRead from `%s`.\n\n", section.Source)
}

func writeWiring(doc *strings.Builder, d Data) {
	doc.WriteString("## What decides what today\n\n")
	fmt.Fprintf(doc, "%s decide anything when you run tofu today, read from `%s`.\n\n", d.PointsOn(), d.MethodTable)
	doc.WriteString("| What decides | Switched on | What it costs | Why | Called by | Measured |\n|---|---|---|---|---|---|\n")
	for _, row := range d.Wiring {
		fmt.Fprintf(doc, "| `%s` | %s | %s | %s | %s | %s |\n",
			row.Point, row.SwitchedOn, cell(row.Costs), cell(row.Why), cell(row.CalledBy), cell(row.Measured))
	}
	doc.WriteString("\n")
}

func writeJudgments(doc *strings.Builder, rows []JudgmentRow) {
	doc.WriteString("## Which decisions Jev wins, which it loses, and by how much\n\n")
	doc.WriteString("| What decides | Method | Method | Winner | By how much | Measured on | Switched on | Report |\n|---|---|---|---|---|---|---|---|\n")
	for _, row := range rows {
		without, with, winner, much := "not compared", "not compared", "not compared", "not compared"
		if row.Compared() {
			without = row.Without.Name + " " + string(row.Without.Reading) + ", which " + row.Without.Does
			with = row.With.Name + " " + string(row.With.Reading) + ", which " + row.With.Does
			winner, much = row.Winner, string(row.Gap)+", "+string(row.Multiple)
		}
		fmt.Fprintf(doc, "| %s, `%s`, %s | %s | %s | %s | %s | %s | %s | `%s` |\n",
			row.Question, row.Point, row.Axis, cell(without), cell(with), winner, much, row.Sample, row.SwitchedOn, row.Source)
	}
	doc.WriteString("\nWhy the rest are not compared:\n\n")
	for _, row := range rows {
		if !row.Compared() {
			fmt.Fprintf(doc, "- **%s**: %s\n", row.Question, row.NotCompared)
		}
	}
	doc.WriteString("\n")
}

func writeReports(doc *strings.Builder, d Data) {
	doc.WriteString("## Every dated report, newest first\n\n")
	fmt.Fprintf(doc, "%s over %s. %s carry none. %s withdrawn whole or in part, %s stale, and %s name no conclusion a reader can find. A withdrawal declared from outside a report lives in `%s`; every other state is declared by the report's own first lines.\n\n",
		countFigure(d.Counts.Reports, "dated reports"), countFigure(d.Counts.MeasuredPackage, "benches"),
		countFigure(d.Counts.NoReport, "benches"), countFigure(d.Counts.Withdrawn, "are"),
		countFigure(d.Counts.Stale, "is"), countFigure(d.Counts.Unparsed, "reports"), d.WithdrawalsLiveIn)
	doc.WriteString("| Bench | Date | Report | What it found | Sample | State |\n|---|---|---|---|---|---|\n")
	for _, report := range d.Reports {
		fmt.Fprintf(doc, "| %s | %s | `%s` | %s | %s | %s |\n",
			report.Package, report.Date, report.Source, cell(report.Quoted()), cell(report.Sample), report.State)
	}
	doc.WriteString("\n### Not standing\n\n")
	for _, report := range d.Reports {
		if report.State.Stands() {
			continue
		}
		fmt.Fprintf(doc, "- `%s` is %s, said by %s: %s\n", report.Source, report.State, report.StateSource, cell(report.StateNote))
	}
	doc.WriteString("\n### Benches with no dated report\n\n")
	for _, pkg := range d.NoReport {
		fmt.Fprintf(doc, "- `bench/%s`, %s: %s\n", pkg.Package, pkg.Kind, pkg.Note)
	}
	doc.WriteString("\n### Where these reports came from\n\n")
	rerun := 0
	for _, report := range d.Reports {
		if report.BuiltFrom == FromRerun {
			rerun++
		}
	}
	fmt.Fprintf(doc, "%d of %d reports are built by running the package's own code again and %d of %d from the markdown's own text, which is weaker evidence, and every one of those says so.\n",
		rerun, len(d.Reports), len(d.Reports)-rerun, len(d.Reports))
}

func cell(text string) string {
	if text == "" {
		return "not stated"
	}
	return strings.ReplaceAll(strings.ReplaceAll(text, "|", "\\|"), "\n", " ")
}
