#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Group {
    Foundations,
    Lists,
    Controls,
    Overlays,
    Content,
    Layout,
}

impl Group {
    pub const ALL: [Group; 6] = [
        Group::Foundations,
        Group::Lists,
        Group::Controls,
        Group::Overlays,
        Group::Content,
        Group::Layout,
    ];

    pub fn title(self) -> &'static str {
        match self {
            Group::Foundations => "Foundations",
            Group::Lists => "Lists",
            Group::Controls => "Controls",
            Group::Overlays => "Overlays",
            Group::Content => "Content",
            Group::Layout => "Layout",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Page {
    Type,
    Icons,
    Surfaces,
    Motion,
    Tabs,
    Row,
    Table,
    Feed,
    Avatar,
    Chip,
    Button,
    Input,
    Segmented,
    Switch,
    Focus,
    Popover,
    Menu,
    Dropdown,
    ContextMenu,
    Toast,
    Sheet,
    Drawer,
    Palette,
    Tooltips,
    Empty,
    Composer,
    Shell,
    Diff,
    ChatRows,
    FileTree,
    History,
    Shells,
    Terminal,
    AskBar,
    Agents,
    FileEdits,
    Charts,
    Delegation,
    Tiling,
}

pub struct Sheet {
    pub slug: &'static str,
    pub title: &'static str,
    pub group: Group,
    pub about: &'static str,
    pub boards: &'static str,
    pub source: &'static str,
    pub states: &'static str,
    pub missing: &'static str,
}

pub const UNBUILT: [(Group, &str); 10] = [
    (Group::Foundations, "Theme classes"),
    (Group::Foundations, "Theme preview"),
    (Group::Foundations, "Intro background"),
    (Group::Lists, "Sidebar rows"),
    (Group::Controls, "Window controls"),
    (Group::Controls, "Scrollbar"),
    (Group::Controls, "Progress bar"),
    (Group::Content, "Status bar"),
    (Group::Content, "Code and editor"),
    (Group::Content, "Sections"),
];

impl Page {
    pub const ALL: [Page; 39] = [
        Page::Type,
        Page::Icons,
        Page::Surfaces,
        Page::Motion,
        Page::Tabs,
        Page::Row,
        Page::Table,
        Page::Feed,
        Page::ChatRows,
        Page::FileTree,
        Page::History,
        Page::Agents,
        Page::FileEdits,
        Page::Avatar,
        Page::Chip,
        Page::Button,
        Page::Input,
        Page::Segmented,
        Page::Switch,
        Page::Focus,
        Page::Popover,
        Page::Menu,
        Page::Dropdown,
        Page::ContextMenu,
        Page::Toast,
        Page::Sheet,
        Page::Drawer,
        Page::Palette,
        Page::Tooltips,
        Page::Empty,
        Page::Composer,
        Page::Shell,
        Page::Diff,
        Page::Shells,
        Page::Terminal,
        Page::AskBar,
        Page::Charts,
        Page::Delegation,
        Page::Tiling,
    ];

    pub fn parse(slug: &str) -> Option<Page> {
        Page::ALL.into_iter().find(|page| page.sheet().slug == slug)
    }

    pub fn sheet(self) -> Sheet {
        let sheet = |slug, title, group, about, boards, source, states, missing| Sheet {
            slug,
            title,
            group,
            about,
            boards,
            source,
            states,
            missing,
        };
        match self {
            Page::Type => sheet(
                "type",
                "Type",
                Group::Foundations,
                "The font sizes and the text alpha scale every component draws with.",
                "IWY-4, W208",
                "components/size.rs",
                "static",
                "",
            ),
            Page::Icons => sheet(
                "icons",
                "Icons",
                Group::Foundations,
                "Line icons for chrome and glyphs for content, drawn from one stroke set.",
                "IWY-4, W208",
                "icon.rs, components/glyph.rs",
                "rest, hover on an icon button",
                "press, focus, disabled",
            ),
            Page::Surfaces => sheet(
                "surfaces",
                "Surfaces",
                Group::Foundations,
                "The shell, its header, the inner card and the dot field every tile sits in.",
                "ITHEME-1; header ICHAT-1 ICHAT-2 ICHAT-4 IGIT-1 ISET-1 IDATA-1; inner ISET-1 IEDITOR-1 IDATA-1; dots IWV-7 ISESSION-2 IJEV-2 ILIMITS-1 IUSAGE-1",
                "components/card.rs",
                "title header, tabbed header, trailing control",
                "",
            ),
            Page::Motion => sheet(
                "motion",
                "Motion",
                Group::Foundations,
                "Live demos of every motion the app uses, each with its tokens. Replay one, or all of them at once.",
                "motion-spec.md",
                "desk_motion: tokens, Presence; gpui SpringConfig",
                "eased against spring, presence, stagger, reflow, shared element, drag and throw, reduced motion",
                "",
            ),
            Page::Tabs => sheet(
                "tabs",
                "Tabs",
                Group::Lists,
                "Connected tabs inside a tile header and workspace tabs in the title bar.",
                "W208 IWY-4 ICHAT-1 ICHAT-3 ITHEME-1 ITV-1 IWIN-1 IWY-9 IBROWSER-1 IEDITOR-1 IEDITOR-2 IEDITOR-3; workspace S-FRAME",
                "components/tabs.rs",
                "rest, hover, selected, close-box hover, close, pinned, locked, count, overflow",
                "press, focus, disabled",
            ),
            Page::Row => sheet(
                "row",
                "Row",
                Group::Lists,
                "A list row, a group header that folds, and the separator between them.",
                "ISET-1 W208 IEDITOR-1 IGIT-1 IWY-4 ICHAT-1",
                "components/list.rs",
                "rest, hover, selected, focused, group open, group closed",
                "press, disabled, empty",
            ),
            Page::Table => sheet(
                "table",
                "Table",
                Group::Lists,
                "A data grid over 5,000 rows, virtualised.",
                "IDATA-1 ISET-1",
                "components/list.rs",
                "rest, hover, selected",
                "focus, empty, loading",
            ),
            Page::Feed => sheet(
                "feed",
                "Feed",
                Group::Lists,
                "One line per agent action, in a list that only lays out what is visible.",
                "W208 IWY-4 IWY-7 IWY-8",
                "components/feed.rs, components/list.rs",
                "every event kind, failure",
                "empty, loading",
            ),
            Page::Avatar => sheet(
                "avatar",
                "Avatar",
                Group::Controls,
                "Who an agent is and what it is doing, with the spinner for work in flight.",
                "IWY-4 ITHEME-1 W208 ICHAT-1 ITV-1 IWIN-1 IWY-7 IWY-8; spinner ICHAT-1",
                "components/avatar.rs",
                "working, asking, failed, finished; sizes feed, list, row, large",
                "",
            ),
            Page::Chip => sheet(
                "chip",
                "Chip and Badge",
                Group::Controls,
                "Small labelled things: chips, file chips, code, keys, mentions, badges, trace.",
                "ISET-1 ICHAT-1 ICHAT-2 ICHAT-4 ICHAT-5 IEDITOR-2 ISESSION-1 IWY-4 W208; badge ISET-1",
                "components/chip.rs",
                "rest, hover on flat chip, mention and trace, git status, tone",
                "press, focus, disabled",
            ),
            Page::Button => sheet(
                "button",
                "Button",
                Group::Controls,
                "The one action control: plain, primary and icon.",
                "IGIT-1",
                "components/button.rs, component.rs",
                "rest, hover (plain and icon)",
                "press, focus, disabled, loading",
            ),
            Page::Input => sheet(
                "input",
                "Input",
                Group::Controls,
                "A one-line text field.",
                "F1 ISET-1 IBROWSER-1 IDATA-1 IGIT-1 ICHAT-1",
                "components/form.rs",
                "empty, filled, focused",
                "hover, disabled, error",
            ),
            Page::Segmented => sheet(
                "segmented",
                "Segmented",
                Group::Controls,
                "A choice of one among a few, side by side.",
                "ISET-1 IBROWSER-1 ITHEME-1 ICHAT-1 IGIT-1",
                "components/form.rs",
                "selected, hover on the others",
                "press, focus, disabled",
            ),
            Page::Switch => sheet(
                "switch",
                "Switch",
                Group::Controls,
                "On or off, with its label.",
                "ISET-1 ICHAT-1",
                "components/form.rs",
                "on, off, track fade",
                "hover, press, focus, disabled",
            ),
            Page::Focus => sheet(
                "focus",
                "Focus",
                Group::Controls,
                "Tab and Shift Tab move through a button, a segmented, a switch and tabs. Enter and Space press the button and flip the switch, Left and Right move the choice and the tab. The ring shows only when focus came from the keyboard.",
                "13-keyboard.md",
                "components/paint.rs focus_ring, arrowed; button.rs, form.rs, tabs.rs",
                "focused from the keyboard with the ring, focused by a click without it, activation by Enter, Space and arrows",
                "",
            ),
            Page::Popover => sheet(
                "popover",
                "Popover",
                Group::Overlays,
                "A panel beside its anchor, on the side that has room.",
                "IEDITOR-1 ICHAT-1 S-FRAME-1 S-FRAME-2",
                "components/overlay.rs Popover",
                "closed, opening, open, closing, flipped",
                "",
            ),
            Page::Menu => sheet(
                "menu",
                "Menu",
                Group::Overlays,
                "A list of actions opened from a button.",
                "IEDITOR-1 ICHAT-1 S-FRAME-1",
                "components/overlay.rs menu",
                "row hover, keys, pick",
                "disabled item",
            ),
            Page::Dropdown => sheet(
                "dropdown",
                "Dropdown",
                Group::Overlays,
                "A choice of one, opened from its badge. Arrows move, Enter picks, Escape closes.",
                "ICHAT-1 S-FRAME-2",
                "components/overlay.rs Dropdown",
                "closed, open, highlighted, picked",
                "",
            ),
            Page::ContextMenu => sheet(
                "context-menu",
                "Context menu",
                Group::Overlays,
                "The menu a right click opens at the pointer.",
                "IEDITOR-1",
                "components/overlay.rs context_menu",
                "closed, open at the pointer, pick",
                "",
            ),
            Page::Toast => sheet(
                "toast",
                "Toast",
                Group::Overlays,
                "Notices stacked in the corner, newest in front. Hover spreads them; each leaves on its own timer, its \u{d7} or a swipe.",
                "S-FRAME, sonner",
                "components/overlay.rs Toaster",
                "success, error, info, loading that resolves, stacked, expanded, swipe, dismiss",
                "",
            ),
            Page::Sheet => sheet(
                "sheet",
                "Sheet",
                Group::Overlays,
                "A modal panel from an edge, closed by Cancel, Confirm or a click outside.",
                "W208",
                "components/sheet.rs Sheet",
                "entering, open, cancel, confirm, click outside",
                "",
            ),
            Page::Drawer => sheet(
                "drawer",
                "Drawer",
                Group::Overlays,
                "A panel from the bottom edge with a knob to drag it closed.",
                "W208",
                "components/sheet.rs Drawer",
                "entering, open, dragged, closed",
                "",
            ),
            Page::Palette => sheet(
                "palette",
                "Palette",
                Group::Overlays,
                "Ctrl K on every platform: a field that filters every command by its label, grouped in the caller's order. Up and Down move, Enter or a click picks, Escape or a click outside closes.",
                "04-ui-model.md Palette, 13-keyboard.md",
                "components/palette.rs; form.rs TextArea, list.rs HoverList, overlay.rs menu_surface, chip.rs kbd",
                "closed, open with six groups, filtered, nothing found, highlighted by keys and pointer, picked, closed by Escape or outside click",
                "keeping the highlighted row in view when the list is taller than the panel: ScrollArea keeps its handle private",
            ),
            Page::Tooltips => sheet(
                "tooltips",
                "Tooltips",
                Group::Overlays,
                "A tooltip names what a control does; a hover card shows more about a name and holds its own actions.",
                "S-FRAME",
                "components/tooltip.rs tooltip, hover_card",
                "icon buttons packed edge to edge, inline words, avatars, agent names with hover cards, corners at the window edge",
                "",
            ),
            Page::Empty => sheet(
                "empty-state",
                "Empty state",
                Group::Content,
                "What a surface shows with nothing in it: a title, a line, actions with their keys and the shortcuts that apply.",
                "15-tiling.md",
                "components/empty.rs",
                "title only, title with line and actions, empty workspace with hints",
                "",
            ),
            Page::Composer => sheet(
                "composer",
                "Composer",
                Group::Content,
                "Where a person writes to the lead.",
                "W208 IBROWSER-1 IWY-4 ICHAT-1",
                "components/composer.rs",
                "empty, typing with a mention",
                "focus, disabled, sending",
            ),
            Page::Shell => sheet(
                "shell",
                "Shell",
                Group::Content,
                "A command and the output it printed.",
                "W208 IWY-9",
                "components/term.rs",
                "exit 0, exit 1",
                "running",
            ),
            Page::Diff => sheet(
                "diff",
                "Diff card",
                Group::Content,
                "What changed in one file, hunk by hunk. N and P move between hunks.",
                "IGIT-1 IEDITOR-2",
                "components/diff.rs",
                "hunks, focused hunk, rename, binary, folded large file, opened",
                "",
            ),
            Page::ChatRows => sheet(
                "chat-rows",
                "Chat rows",
                Group::Lists,
                "The rows of a chat: the You bubble, the lead who-line, tool calls folded, sub-agents, failures, notes and the foot.",
                "IWY-4 ICHAT-1 ICHAT-2 ICHAT-3 ICHAT-4 ICHAT-5",
                "components/chat.rs",
                "you, lead, tools folded and open, sub-agent summary, failed command, pending ask, note, foot; board width and 320 px",
                "",
            ),
            Page::FileTree => sheet(
                "file-tree",
                "File tree",
                Group::Lists,
                "The editor's file tree with git state on each row, folders that expand, and a context menu.",
                "IEDITOR-1 IEDITOR-2 IEDITOR-3 S-EDIT",
                "components/tree.rs",
                "expanded, collapsed, six git colours, indent guide, right-edge mark, context menu; board width and 320 px",
                "",
            ),
            Page::History => sheet(
                "history",
                "History",
                Group::Lists,
                "Commits grouped by day, the branch picker, a blame gutter and the changes list.",
                "IGIT-1 IGIT-2 S-GIT",
                "components/history.rs",
                "day groups, agent and person commits, branch picker held during a turn, blame person and agent, staged and unstaged; board width and 320 px",
                "",
            ),
            Page::Shells => sheet(
                "shells",
                "Shells",
                Group::Content,
                "Shells as tabs under the module tabs: a status dot, a mono name, a close on hover, N more with every shell, and the selected shell's output.",
                "IWY-4 IWY-9 S-WORK-7",
                "components/shells.rs, components/width.rs, components/tabs.rs, components/term.rs",
                "running, failed, waiting; N more closed and open; hidden shell picked; pid, starter, port and run time shown wide and hidden under 560 px; Kill calls on_kill; board width and 320 px",
                "",
            ),
            Page::Terminal => sheet(
                "terminal",
                "Terminal",
                Group::Content,
                "The person's own shell: a PTY drawn by desk_terminal inside a tile; an exited process shows its code and Restart.",
                "06-modules.md Terminal",
                "components/terminal.rs, components/card.rs, components/button.rs, components/chip.rs; desk_terminal",
                "running in a scratch folder, typing; exited with code 1 over the dimmed last screen; Restart calls on_restart",
                "split, find, copy and paste, rename; grid colours from the theme",
            ),
            Page::AskBar => sheet(
                "ask-bar",
                "Ask bar",
                Group::Content,
                "The permission card: what wants to run and why, with Allow once, Deny and Always here on keys 1, 2 and 3.",
                "IWY-4 ICHAT-2 ICHAT-4 ICHAT-5",
                "components/ask.rs",
                "asking, answered in place, waiting on you; board width and 320 px",
                "",
            ),
            Page::Agents => sheet(
                "sub-agents",
                "Sub-agents",
                Group::Lists,
                "Every sub-agent grouped by status with counts, what each is doing, and the Sheet a row opens.",
                "IWY-4 IWY-7 IWV-7",
                "components/agents.rs, components/avatar.rs, components/sheet.rs",
                "working, asking, failed, finished; group folded; row opened in the Sheet; board width and 320 px",
                "",
            ),
            Page::FileEdits => sheet(
                "file-edits",
                "File edits",
                Group::Lists,
                "Every file the session edited, one row each with who and when, and the history a row opens: every edit to that file, newest first, each a folding DiffCard.",
                "IWY-4",
                "components/file_edits.rs, components/diff.rs, components/list.rs",
                "12 files, one opened; history of 4 edits with a folded context run; added, modified and deleted files; board width",
                "hunk count per edit: Hunk is private to diff.rs",
            ),
            Page::Charts => sheet(
                "charts",
                "Charts",
                Group::Content,
                "The six charts the boards draw: activity columns, the context window, how it grew, limit meters, Jev sparklines and the session ribbon.",
                "IUSAGE-1 ICONTEXT-1 ILIMITS-1 IJEV-1 ISESSION-2",
                "components/charts.rs",
                "three activity ranges, window before and after compact, compaction drop, spent and warning meters, hover tooltips; board width and 320 px",
                "",
            ),
            Page::Delegation => sheet(
                "delegation",
                "Delegation",
                Group::Content,
                "The lead, the agents it delegated to and the files each one changed, with the cross link between them.",
                "IWV-7",
                "components/graph.rs",
                "nothing picked, agent picked with its cross link, file picked and undone, edge hover; board width and 320 px",
                "",
            ),
            Page::Tiling => sheet(
                "tiling",
                "Tiling",
                Group::Layout,
                "Workspaces of tiles: spawn, drop on a tile or a workspace edge, resize, nudge, swap, zoom, close and undo.",
                "15-tiling.md",
                "desk_tiling",
                "preset workspaces, empty workspace, header drag with zone and edge previews, divider drag, zoom, refusal",
                "",
            ),
        }
    }
}
